# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(max_length=120)),
                ('away', models.CharField(max_length=120)),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('status', models.CharField(max_length=120)),
            ],
        ),
    ]
