# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_game'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='Match',
        ),
    ]
