# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170120_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Tournament'),
            preserve_default=False,
        ),
    ]
