# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import djchoices.choices


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170120_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('active', 'active'), ('completed', 'completed')], default='scheduled', max_length=50, validators=[djchoices.choices.ChoicesValidator({'active': 'active', 'completed': 'completed', 'scheduled': 'scheduled'})]),
        ),
    ]
