# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170120_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away', to='api.Profile'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='api.Profile'),
        ),
    ]
