# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170120_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='realName',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
