# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_team_realname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='realName',
            new_name='real_name',
        ),
    ]
